name: minecraft_info_provider
description: Pure Dart Minecraft local information provider and Java Edition NBT toolkit.
version: 1.0.0-dev.5
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
