name: minecraft_content_service
description: Pure Dart Minecraft content catalog, provider, version, dependency, and relation service foundation.
version: 1.0.0-dev.27
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  crypto: ^3.0.7
  http: ^1.2.2
  path: ^1.9.1
  remvibe_download_service:
    git:
      url: https://github.com/nusretm/remvibe_download_service
      ref: main

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
